### ISSUE TITLE
Table and plot from one control?

### ISSUE THREAD

**Issue by ralphschreyer** [adamhajari/spyre#16]
Hi there,

this is rather a question than an issue, but maybe there is a simple answer to it.

Assume that it is quite expensive to calculate some data. Is there a way to have just one control button which starts the calculation and then displays the data in a table and thereafter displays the data in a plot without having the calculation done twice, like in the code below (which of course does not work since getPlot does not know to wait for getData ...)?

Hope this is not a too silly question. Thanks a lot.

Ralph

```python
import pandas
from spyre import server
import time       

def calculate():
    time.sleep(5)
    data = {'x': range(100), 'y': range(100)}
    df = pandas.DataFrame(data, columns = ['x', 'y'])
    return df
   
class SlowDummyApp(server.App):
    title = 'Slow Dummy'
    controls = [
        {
            'control_type' : 'button',
            'label'        : 'Calculate',
            'control_id'   : 'calculate'
        },
    ]
    outputs = [
        {
            'output_type'  : 'table',
            'output_id'    : 'table_id',
            'tab'          : 'Data',
            'control_id'   : 'calculate',
            'on_page_load' : False 
        },
        {
            'output_type'  : 'plot',
            'output_id'    : 'plot_id',
            'tab'          : 'Plot',
            'control_id'   : 'calculate',
            'on_page_load' : False 
        },
    ]
    tabs = ['Data', 'Plot']

    def getData(self, params):
        self.df = calculate()
        return self.df
  
    def getPlot(self, params):
        fig = self.df.plot().get_figure()
        return fig

app = SlowDummyApp()
app.launch(host='local')
```

**Comment by adamhajari** [comment]
@ralphschreyer this is a great question. Unfortunately there's not a *simple* solution to this problem since the requests get made asynchronously. However, I just pushed an update to the stocks_example app which implements a caching mechanism that you might find useful: https://github.com/adamhajari/spyre/blob/master/examples/stocks_example.py

Here's how it works:
1. initialize two caching variables, one for your data and one for your params
2. have your getData method update the cached data and the cached params (after dropping the output_id key in the params dict).
3. have your getPlot method check it's params against the cached params (again, make sure to drop the output_id key). While the cached params and it's params differ, have it wait.
4. once the getPlot method's params match the cached params, have it use the cached data.

**Comment by adamhajari** [comment]
inline comments added here: https://github.com/adamhajari/spyre/commit/488d9fdd8b95273853595a006ae3f50ac0038c03
