### ISSUE TITLE
Help with background

### ISSUE THREAD

**Issue by LuisSoares** [adamhajari/spyre#32]
I am sorry if this seems a basic question, but I have been using spyre and I think is awesome, but my knowledge of CherryPi is very limited. My question is regarding adding pictures to the background of the html. I changed the CustomView class to use my own html template and css, however when I try to add a local file as a background (or even as a favico) the server doesn't seem to find the file on the root directory. Maybe this is more related to cherryPi than spyre but does anybody know how this can be achieved?

**Comment by adamhajari** [comment]
@LuisSoares the easiest way to do this is to host the image somewhere else (S3, photobucket, etc.) and reference that image within the getCussomCSS method. Here's an example using a photo I uploaded to photobucket (here: http://s95.photobucket.com/user/adamjdanger/media/indonesia_bg.jpg.html)

```python
from spyre import server

class SimpleApp(server.App):
    
    title = "Simple App"
    inputs = [{ "type":"text",
                "key":"words",
                "label":"write words here",
                "value":"hello world", 
                "action_id":"simple_html_output"}]

    outputs = [{"type":"html",
                "id":"simple_html_output"}]

    def getHTML(self, params):
        words = params["words"]
        return "Here's what you wrote in the textbox: <b>%s</b>" % words

    def getCustomCSS(self):
        css = """body { background-image: url("http://i95.photobucket.com/albums/l141/adamjdanger/indonesia_bg.jpg");}"""
        return css

app = SimpleApp()
app.launch()
```

If you wanted a completely self-contained app (that worked without internet access) you could create an endpoint for your image. Make sure the image you're using as the background is in the same directory you are launching your app from and add a  `getImage` method to your app and an additional output of type `image`. Here's an example:

```python
from spyre import server
import matplotlib.image as mpimg

class SimpleApp(server.App):
    
    title = "Simple App"
    inputs = [{ "type":"text",
                "key":"words",
                "label":"write words here",
                "value":"hello world", 
                "action_id":"simple_html_output"}]

    outputs = [{"type":"html",
                "id":"simple_html_output"},
               {"type" : "image",
                "id" : "bg_image",
                "on_page_load" : False}]

    def getHTML(self, params):
        words = params["words"]
        return "Here's what you wrote in the textbox: <b>%s</b>" % words

    def getCustomCSS(self):
        css = """body { background-image: url("image?output_id=bg_image");}"""
        return css

    def getImage(self, params):
        img = mpimg.imread('indonesia_bg.jpg')
        return img

app = SimpleApp()
app.launch()
```

A couple of things to note here. Make sure you import `matplotlib.image`. Also, make sure you set the attribute `on_page_load` to `False` for the image output (otherwise it will try to load as an output and your background). Finally the url you specify in the css is `image?output_id=bg_image` where "bg_image" was the output_id we specified in our output's attributes.
